version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '5000:5000'
    tty: true
    networks:
      - example-ssl

  ngnix:
    build:
      context: .
      dockerfile: ngnixdockerfile
    ports:
      - '80:80'
      - '443:443'
    tty: true
    volumes: 
      # - ./certbot/conf:/etc/letsencrypt
      - ./certbot:/var/www/certbot
    depends_on:
      - api
      # - certbot
    networks:
      - example-ssl

  # certbot:
  #   image: certbot/certbot:latest
  #   # entrypoint: "/bin/sh -c 'certbot -d compcon.com.br -d api.compcon.com.br --email alissonvsouza8@gmail.com --agree-tos --manual --preferred-challenges dns certonly'"
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/logs:/var/log/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   networks:
  #     - example-ssl

networks:
  example-ssl:
    external: true